/*
  # Product Schema Setup
  
  1. Enums
    - gender: For product gender targeting (male, female, unisex)
    - category: Product types (crew_tshirt, hoodie, cropped_hoodie, oversized_tshirt)
    - size: Standard clothing sizes (xs through xxl)
    - taxRate: GST rates for different product categories
  
  2. Tables
    - product: Main product table with all product details
      - Basic info (name, description, slug, sku)
      - Pricing (price, discount, salePrice)
      - Categorization (gender, category, size)
      - Media (images array)
      - Status flags (isNew, isFeatured, isOnSale, inStock)
      - Tax info (taxRate)
      - Timestamps (createdAt, updatedAt)
*/

-- Step 1: Create enums
create type public.gender as enum ('male', 'female', 'unisex');
create type public.category as enum ('crew_tshirt', 'hoodie', 'cropped_hoodie', 'oversized_tshirt');
create type public.size as enum ('xs', 's', 'm', 'l', 'xl', 'xxl');
create type public.taxRate as enum ('GST_5', 'GST_12', 'GST_18', 'GST_28');

-- Step 2: Create the main product table
create table if not exists public.product (
  id bigint generated by default as identity primary key,
  name varchar not null unique,
  description text,
  slug varchar not null unique,
  sku varchar not null unique,
  price numeric not null,
  discount numeric,
  salePrice numeric,
  gender public.gender,
  category public.category,
  size public.size,
  images text[],
  isNew boolean default false,
  isFeatured boolean default false,
  isOnSale boolean default false,
  inStock boolean default true,
  taxRate public.taxRate,
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now()
);