/*
  # Migrations Tracking Table
  
  1. Purpose
    - Tracks all database migrations that have been applied
    - Prevents duplicate migration execution
    - Maintains migration history
  
  2. Structure
    - id: Unique identifier for each migration
    - name: Name of the migration file
    - created_at: Timestamp when the migration was applied
  
  3. Configuration
    - Uses default PostgreSQL tablespace
    - Includes unique constraints on id
*/

create table if not exists public._migrations (
  id bigint generated by default as identity not null,
  name character varying null,
  created_at timestamp with time zone not null default now(),
  constraint _migrations_pkey primary key (id),
  constraint _migrations_id_key unique (id)
) TABLESPACE pg_default;