create table if not exists public._migrations (
  id bigint generated by default as identity not null,
  name character varying null,
  created_at timestamp with time zone not null default now(),
  constraint _migrations_pkey primary key (id),
  constraint _migrations_id_key unique (id)
) TABLESPACE pg_default;